Resources:
  PortellaVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.42.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: PortellaVPC
  
  PortellaSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref PortellaVPC
      CidrBlock: 10.42.0.0/24
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: Name
          Value: PortellaSubnet1

  PortellaSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref PortellaVPC
      CidrBlock: 10.42.25.0/24
      AvailabilityZone: !Select [1, !GetAZs ""]
      Tags:
        - Key: Name
          Value: PortellaSubnet2

  PortellaKeypair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: !Sub 'key-${AWS::StackName}'
      PublicKeyMaterial: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA7cKbBR1pZO+SALAqrA17WnOK3ULZVG3AICfQdyJ2RC peportella11@gmail.com" 


  PortellaGateway:
    Type: AWS::EC2::InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref PortellaVPC
      InternetGatewayId: !Ref PortellaGateway
  
  PortellaRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref PortellaVPC

  PortellaRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PortellaRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref PortellaGateway

  PortellaSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PortellaSubnet1
      RouteTableId: !Ref PortellaRouteTable

  PortellaSubnetRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PortellaSubnet2
      RouteTableId: !Ref PortellaRouteTable
  
  AppSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Default security group for the CloudProject
      VpcId: !Ref PortellaVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8000'
          ToPort: '8000'
          CidrIp: 0.0.0.0/0

      SecurityGroupEgress:
        - IpProtocol: '-1'
          CidrIp: 0.0.0.0/0
    
  PortellaEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      IamInstanceProfile: !Ref DynamoDBAccessInstanceProfile
      AvailabilityZone: !Select [0, !GetAZs ""]
      ImageId: ami-04b70fa74e45c3917
      KeyName: !Ref PortellaKeypair
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: '0'
          GroupSet:
            - !Ref AppSecurityGroup
          SubnetId: !Ref PortellaSubnet1
      Tags:
        - Key: Name
          Value: PortellaEC2Instance

  PortellaDynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      TableName: BolaoTable
      AttributeDefinitions:
        -
          AttributeName: Name
          AttributeType: S
      KeySchema:
        -
          AttributeName: Name
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  DynamoDBAccessRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: DynamoDBAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: dynamodb:*
                Resource: !GetAtt PortellaDynamoDBTable.Arn

  DynamoDBAccessInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: "/"
      Roles:
        - !Ref DynamoDBAccessRole